name: Deploy to EC2 using AWS CodeDeploy

on:
  push:
    branches:
      - main # Change to your default branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Zip Application for Deployment
        run: zip -r deploy.zip . -x "*.git*"

      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: |
          aws s3 cp deploy.zip s3://my-app-bucket-123/deploy.zip

      - name: Trigger CodeDeploy Deployment
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: |
          aws deploy create-deployment \
            --application-name MyApp-Deployment \
            --deployment-group-name MyDeploymentGroup \
            --s3-location bucket=my-app-bucket-123,key=deploy.zip,bundleType=zip
